# Generated by Django 5.0.6 on 2024-06-26 18:06

import park.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.IntegerField(validators=[park.models.validate_positive]),
        ),
    ]
