# Generated by Django 5.0.6 on 2024-08-19 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kaspi', '0002_good_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='KaspiShop',
        ),
        migrations.CreateModel(
            name='RevKaspiShop',
            fields=[
            ],
            options={
                'ordering': ['created_date'],
                'proxy': (True,),
                'indexes': [],
                'constraints': [],
            },
            bases=('kaspi.kaspishop',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
